from sqlalchemy import Column, Integer, String, Float, DateTime
from datetime import datetime
from app.core.database import Base

class MatchedStone(Base):
    __tablename__ = 'matched_stones'
    id = Column(Integer, primary_key=True, autoincrement=True)
    vdb_stone_id = Column(String)
    diamax_stone_id = Column(String)
    shape = Column(String)
    carat = Column(Float)
    color = Column(String)
    clarity = Column(String)
    cut = Column(String)
    polish = Column(String)
    symmetry = Column(String)
    fluorescence = Column(String)
    lab = Column(String)
    country = Column(String)
    vdb_price = Column(Float)
    vdb_price_per_carat = Column(Float)
    diamax_price = Column(Float)
    diamax_price_per_carat = Column(Float)
    market_difference = Column(Float)
    profit_margin_pct = Column(Float)
    buy_price = Column(Float)
    max_buy_price = Column(Float)
    min_sell_price = Column(Float)
    recommended_sell_price = Column(Float)
    premium_sell_price = Column(Float)
    expected_profit = Column(Float)
    confidence_score = Column(Float)
    risk_adjusted_profit = Column(Float)
    composite_buy_score = Column(Float)
    holding_period_days = Column(Integer)
    recommendation = Column(String)
    stars = Column(Integer, default=1)
    negotiation_range_low = Column(Float)
    negotiation_range_high = Column(Float)
    matched_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
