import { useEffect, useMemo, useState } from 'react';
import { BarChart3 } from 'lucide-react';
import { getShapeStockVsSales, ShapeStockVsSales } from '../api/client';
import { Spinner } from '../components/ui/Spinner';

const number = (value: number, digits = 0) => value.toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits });

export const ShapeAnalysis = () => {
  const [rows, setRows] = useState<ShapeStockVsSales[]>([]);
  useEffect(() => { getShapeStockVsSales().then(result => setRows(result.items)); }, []);
  const totals = useMemo(() => rows.reduce((sum, row) => ({
    stockPcs: sum.stockPcs + row.stock_pcs, stockWeight: sum.stockWeight + row.stock_weight, stockAmount: sum.stockAmount + row.stock_amount,
    salesPcs: sum.salesPcs + row.sales_pcs, salesWeight: sum.salesWeight + row.sales_weight, salesAmount: sum.salesAmount + row.sales_amount,
  }), { stockPcs: 0, stockWeight: 0, stockAmount: 0, salesPcs: 0, salesWeight: 0, salesAmount: 0 }), [rows]);
  if (!rows.length) return <div className="flex min-h-[400px] items-center justify-center"><Spinner size="lg" /></div>;
  const salesPct = totals.stockPcs ? totals.salesPcs / totals.stockPcs * 100 : 0;

  return <div className="flex h-[calc(100vh-7rem)] min-h-[520px] flex-col gap-2 overflow-hidden animate-fade-in">
    <div className="glass-card flex shrink-0 items-center gap-3 px-3 py-2"><div className="rounded-md bg-cyan-500/15 p-1.5"><BarChart3 className="h-4 w-4 text-cyan-300" /></div><div><h1 className="text-sm font-black text-white">Shape: Stock vs Sale Report</h1><p className="text-[10px] text-slate-400">All {rows.length} available shapes. Sales % = sold pieces / current stock pieces.</p></div><span className="ml-auto text-xs font-black text-amber-300">Total: {number(salesPct, 1)}%</span></div>
    <div className="flex-1 overflow-hidden rounded-lg border border-slate-500/40 bg-slate-100 text-slate-900 shadow-xl">
      <table className="shape-report-table h-full w-full table-fixed border-collapse text-[10px] leading-none">
        <colgroup><col className="w-[25%]" /><col className="w-[7%]" /><col className="w-[9%]" /><col className="w-[7%]" /><col className="w-[13%]" /><col className="w-[7%]" /><col className="w-[9%]" /><col className="w-[7%]" /><col className="w-[13%]" /><col className="w-[7%]" /></colgroup>
        <thead className="bg-gradient-to-b from-slate-100 to-blue-100 text-[#06386b]"><tr className="h-6"><th rowSpan={2} className="border border-slate-400 px-1.5 text-left">Shape</th><th rowSpan={2} className="border border-slate-400 px-1 text-right">Stock<br />Pcs</th><th rowSpan={2} className="border border-slate-400 px-1 text-right">Stock<br />Weight</th><th colSpan={2} className="border border-slate-400 px-1 text-center">Stock</th><th rowSpan={2} className="border border-slate-400 px-1 text-right">Sales<br />Pcs</th><th rowSpan={2} className="border border-slate-400 px-1 text-right">Sales<br />Weight</th><th colSpan={2} className="border border-slate-400 px-1 text-center">Sale</th><th rowSpan={2} className="border border-slate-400 px-1 text-right">Sales<br />%</th></tr><tr className="h-5"><th className="border border-slate-400 px-1 text-right">Web Rate</th><th className="border border-slate-400 px-1 text-right">Web Amount</th><th className="border border-slate-400 px-1 text-right">Sales Rate</th><th className="border border-slate-400 px-1 text-right">Sale Amount</th></tr></thead>
        <tbody className="!text-slate-900">{rows.map((row, index) => <tr key={row.shape} className={`h-[17px] !text-slate-900 border-b border-slate-300 ${index === 0 ? 'bg-blue-100 font-bold' : 'bg-white hover:bg-blue-50'}`}><td className="border border-slate-300 px-1.5 font-semibold !text-slate-950">{row.shape}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.stock_pcs)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.stock_weight, 2)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.stock_rate, 2)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.stock_amount, 2)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.sales_pcs)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.sales_weight, 2)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.sales_rate, 2)}</td><td className="border border-slate-300 px-1 text-right !text-slate-900">{number(row.sales_amount, 2)}</td><td className="border border-slate-300 px-1 text-right font-bold !text-[#06386b]">{number(row.sales_percentage, 1)}%</td></tr>)}</tbody>
        <tfoot className="h-[18px] bg-blue-50 font-black text-[#062f5b]"><tr><td className="border border-slate-400 px-1.5 text-right">Total</td><td className="border border-slate-400 px-1 text-right">{number(totals.stockPcs)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.stockWeight, 2)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.stockWeight ? totals.stockAmount / totals.stockWeight : 0, 2)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.stockAmount, 2)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.salesPcs)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.salesWeight, 2)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.salesWeight ? totals.salesAmount / totals.salesWeight : 0, 2)}</td><td className="border border-slate-400 px-1 text-right">{number(totals.salesAmount, 2)}</td><td className="border border-slate-400 px-1 text-right">{number(salesPct, 1)}%</td></tr></tfoot>
      </table>
    </div>
    <style>{`.shape-report-table thead, .shape-report-table thead th { background: #dbeafe !important; color: #062f5b !important; opacity: 1 !important; } .shape-report-table tbody tr { background: #ffffff !important; color: #0f172a !important; opacity: 1 !important; } .shape-report-table tbody tr:first-child { background: #dbeafe !important; } .shape-report-table tbody td { color: #0f172a !important; opacity: 1 !important; } .shape-report-table tbody td:last-child { color: #06386b !important; } .shape-report-table tfoot, .shape-report-table tfoot td { background: #dbeafe !important; color: #062f5b !important; opacity: 1 !important; }`}</style>
  </div>;
};
